### ISSUE TITLE
Crash on jump with Advanced Solars onboard

### ISSUE THREAD

**Issue by Maxstripe** [StargateMC/StargateMCPublic#174]
Dimension: SPACE
X:23052,Z:17187,Y:71
290 blocks south
player: Nosknut
he cannot log back in rn because he jumped with a hybrid solar on his ship and the server crashes everytime he logs in

**Comment by DraksterAU** [comment]
Server Crash report: 

---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 31/08/16 15:30
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
        at ic2.core.energy.Grid.merge(Grid.java:227)
        at ic2.core.energy.EnergyNetLocal.addTileToGrids(EnergyNetLocal.java:544)
        at ic2.core.energy.EnergyNetLocal.addTileEntity(EnergyNetLocal.java:185)
        at ic2.core.energy.EnergyNetLocal.addTileEntity(EnergyNetLocal.java:66)
        at ic2.core.energy.EventHandler.onEnergyTileLoad(EventHandler.java:28)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_43_EventHandler_onEnergyTileLoad_EnergyTileLoadEvent.invoke(.dynamic)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
        at ic2.core.block.wiring.TileEntityCable.onLoaded(TileEntityCable.java:159)
        at ic2.core.block.TileEntityBlock$1.tickCallback(TileEntityBlock.java:60)
        at ic2.core.TickHandler.processTickCallbacks(TickHandler.java:175)
        at ic2.core.TickHandler.onWorldTick(TickHandler.java:60)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_25_TickHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
        at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:273)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:957)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
        at java.lang.Thread.run(Thread.java:745)

**Comment by XredstonemodsX** [comment]
perhaps if we have the advanced solars set to jump last, or the cables to jump last?

**Comment by LemADEC** [comment]
It's probably easier to fix advanced solars to fix that one.

**Comment by DraksterAU** [comment]
@LemADEC Agreed. But the TileEntityLoad event throws after the null pointer which makes me have no idea where to look :P

**Comment by LemADEC** [comment]
don't initialize until WorldObj is set in the tile entity

**Comment by DraksterAU** [comment]
Is this something that would need to be fixed in the jump code?

**Comment by LemADEC** [comment]
It's a bug in Advanced Solar Panel and, to some extent IC2 EnergyNet and WarpDrive sequencer.
The easy fix is in ASP. The others would merely be 'work arounds'.
