### ISSUE TITLE
Server Crash: Clearing Unregistered NPCs

### ISSUE THREAD

**Issue by DraksterAU** [StargateMC/StargateMCPublic#187]
Unregistered NPC clearing needs to do things in two phases, just like registered npcs.

First they need to be flagged for removal, then they need to be removed on the next tick.

Crash report below;
```

Time: 06/09/16 22:45
Description: Exception in server tick loop

java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
        at java.util.ArrayList$Itr.next(ArrayList.java:851)
        at thermos.chaud.HashedArrayList$HashedArrayIterator.next(HashedArrayList.java:215)
        at com.stargatemc.mod.providers.npcs.npcRegistry.clearUnregistered(npcRegistry.java:141)
        at com.stargatemc.mod.providers.npcs.npcRegistry.tickNPCs(npcRegistry.java:130)
        at com.stargatemc.mod.StargateMCMod.onWorldTick(StargateMCMod.java:110)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_131_StargateMCMod_onWorldTick_WorldTickEvent.invoke(.dynamic)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
        at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:273)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:957)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
        at java.lang.Thread.run(Thread.java:745)


```

**Comment by DraksterAU** [comment]
This has been replaced by a once/5sec asynchronous task in SEvents.
