### ISSUE TITLE
Placing a wireless redstone item next to an Autonomous Activator results in a crash

### ISSUE THREAD

**Issue by Bysokar** [StargateMC/StargateMCPublic#359]
```
---- Minecraft Crash Report ----
// You're mean.

Time: 29/10/16 23:26
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
        at codechicken.wirelessredstone.addons.RedstoneEtherServerAddons.activateRemote(RedstoneEtherServerAddons.java:69)
        at codechicken.wirelessredstone.addons.ItemWirelessRemote.func_77659_a(ItemWirelessRemote.java:44)
        at codechicken.wirelessredstone.addons.ItemWirelessRemote.onItemUseFirst(ItemWirelessRemote.java:33)
        at cofh.thermalexpansion.block.device.TileActivator.simRightClick2(TileActivator.java:410)
        at cofh.thermalexpansion.block.device.TileActivator.simRightClick(TileActivator.java:367)
        at cofh.thermalexpansion.block.device.TileActivator.doDeploy(TileActivator.java:191)
        at cofh.thermalexpansion.block.device.TileActivator.func_145845_h(TileActivator.java:150)
        at net.minecraft.world.World.func_72939_s(World.java:2548)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:976)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:831)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:683)
        at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
        at codechicken.wirelessredstone.addons.RedstoneEtherServerAddons.activateRemote(RedstoneEtherServerAddons.java:69)
        at codechicken.wirelessredstone.addons.ItemWirelessRemote.func_77659_a(ItemWirelessRemote.java:44)
        at codechicken.wirelessredstone.addons.ItemWirelessRemote.onItemUseFirst(ItemWirelessRemote.java:33)
        at cofh.thermalexpansion.block.device.TileActivator.simRightClick2(TileActivator.java:410)
        at cofh.thermalexpansion.block.device.TileActivator.simRightClick(TileActivator.java:367)
        at cofh.thermalexpansion.block.device.TileActivator.doDeploy(TileActivator.java:191)
        at cofh.thermalexpansion.block.device.TileActivator.func_145845_h(TileActivator.java:150)

-- Block entity being ticked --
Details:
        Name: thermalexpansion.Activator // cofh.thermalexpansion.block.device.TileActivator
        Block type: ID #1339 (tile.thermalexpansion.device // cofh.thermalexpansion.block.device.BlockDevice)
        Block data value: 2 / 0x2 / 0b0010
        Block location: World: (346,6,832), Chunk: (at 10,0,0 in 21,52; contains blocks 336,0,832 to 351,255,847), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
        Actual block type: ID #1339 (tile.thermalexpansion.device // cofh.thermalexpansion.block.device.BlockDevice)
        Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
        at net.minecraft.world.World.func_72939_s(World.java:2548)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673)

-- Affected level --
Details:
        Level name: P2Q-411
        All players: 2 total; [GCEntityPlayerMP['XredstonemodsX'/2190, l='P2Q-411', x=349.51, y=6.00, z=832.84](XredstonemodsX at 349.5123698614085,6.0,832.8411166087004), GCEntityPlayerMP['Bysokar'/44235, l='P2Q-411', x=351.65, y=6.00, z=832.81](Bysokar at 351.645240470767,6.0,832.8127767872761)]
        Chunk stats: ServerChunkCache: 577 Drop: 0
        Level seed: -4512692436169076727
        Level generator: ID 00 - default, ver 1. Features enabled: true
        Level generator options:
        Level spawn location: World: (208,73,482), Chunk: (at 0,4,2 in 13,30; contains blocks 208,0,480 to 223,255,495), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
        Level time: 339243088 game time, 339806141 day time
        Level dimension: 230
        Level storage version: 0x04ABD - Anvil
        Level weather: Rain time: 59993 (now: false), thunder time: 6808 (now: false)
        Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:976)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:831)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:683)
        at java.lang.Thread.run(Thread.java:745)


```

**Comment by Bysokar** [comment]
Fixed.
